FROM node:latest as build-step
RUN mkdir -p /app
WORKDIR /app
COPY . .
#COPY package.json package.json
RUN npm install 
RUN npm run build --prod

FROM nginx:1.19.7-alpine
COPY --from=build-step app/dist/simple-app/* /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80