---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  selector:
    matchLabels:
      app: simple
      tier: backend
      track: stable
  replicas: 1
  template:
    metadata:
      labels:
        app: simple
        tier: backend
        track: stable
    spec:
      containers:
        - name: simple
          image: "thirumurthi/simple-backend:v1"
          ports:
            - name: http
              containerPort: 8080
