---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  selector:
    matchLabels:
      app: simple
      tier: frontend
      track: stable
  replicas: 1
  template:
    metadata:
      labels:
        app: simple
        tier: frontend
        track: stable
    spec:
      containers:
        - name: frontend
          image: "thirumurthi/simple-frontend:v3"
          lifecycle:
            preStop:
              exec:
                command: ["/usr/sbin/nginx","-s","quit"]
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  selector:
    app: simple
    tier: frontend
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 80
  type: LoadBalancer
